### ISSUE TITLE
Repeating serializer error on build

### ISSUE THREAD

**Issue by kkretsch** [nxt3AT/sankeydiagram.net#48] opened 2024-01-31 08:36 UTC
I just git cloned the repo and do run nodejs 20.11.0 LTS

During **npm run build** I repeating get this error:

`@parcel/workers: Expected constructor 2.7.0:BundleGraph to be registered with serializer to deserialize`

Is that nodejs version OK to run it? I didn't find any version requirement in the package json file for this. And what can that error be?

**Comment by JonasDoesThings** [comment] 2024-01-31 17:53
Hey, thanks for reporting @kkretsch 

I've tried with both nodejs v20.11.0 and v18.17.1 and wasn't able to reproduce the issue. But I have bumped the dependency versions and pushed into the dev branch. 

Please check if the error persists with the updated dependencies on branch `dev` after re-running `npm install` and report back
Thanks in advance and have a nice evening :)

**Comment by kkretsch** [comment] 2024-02-01 07:05
Hi, I just pulled the dev branch, did run npm install and then fail now again when running the build step. Same errors here at least.
But I must say it runs under windows 10 which might make things worse as usual.

**Comment by JonasDoesThings** [comment] 2024-02-01 16:24
> Hi, I just pulled the dev branch, did run npm install and now it did finish! Yeahhh

Great to hear that, yeah I'm on MacOS - so maybe that's why I couldn't reproduce the issue. Seems like the problem is gone, so I will close this. 

Feel free to re-open if the issue comes back, happy hacking!

**Closed by JonasDoesThings** 2024-02-01 16:24 UTC
