### ISSUE TITLE
Overlapping graphics need optimization

### ISSUE THREAD

**Issue by wuyang26** [nxt3AT/sankeydiagram.net#55] opened 2024-06-30 04:25 UTC
After conducting some data tests, it has been found that the above libraries perform perfectly for layer by layer data transmission such as A ->B ->C ->D. However, if there is a cross level data transmission such as A ->B and A ->C, the design of graphic avoidance and anti overlap may not perform well, and further optimization may be needed.
    look the data:
    var datas = new List<SankeyData>()
    {
        new SankeyData("United States 1", "Canada", 1.553 * 0.18),
        new SankeyData("United States 1", "Mexico", 1.553 * 0.157),
        new SankeyData("United States 1", "China", 1.553 * 0.084),
        new SankeyData("United States 1", "Japan", 1.553 * 0.044),

        new SankeyData("Germany1", "United States", 1.434 * 0.088),
        new SankeyData("Germany1", "France", 1.434 * 0.082),
        new SankeyData("Germany1", "China", 1.434 * 0.068),
        new SankeyData("Germany1", "Netherlands", 1.434 * 0.067),
        new SankeyData("Germany1", "United Kingdom", 1.434 * 0.066),
        new SankeyData("Germany1", "Italy", 1.434 * 0.051),

        new SankeyData("France1", "Germany", 0.549 * 0.148),
        new SankeyData("France1", "Spain", 0.549 * 0.077),
        new SankeyData("France1", "Italy", 0.549 * 0.075),
        new SankeyData("France1", "United States", 0.549 * 0.072),

        new SankeyData("Italy", "Germany", 0.496 * 0.125),
        new SankeyData("Italy", "France", 0.496 * 0.103),
        new SankeyData("Italy", "United States", 0.496 * 0.09),

        new SankeyData("United Kingdom", "United States", 0.441 * 0.132),
        new SankeyData("United Kingdom", "Germany", 0.441 * 0.105),
        new SankeyData("United Kingdom", "France", 0.441 * 0.074),
        new SankeyData("United Kingdom", "Netherlands", 0.441 * 0.062),

        new SankeyData("Canada", "United States", 0.4235 * 0.764),
        new SankeyData("Canada", "China", 0.4235 * 0.043),

        new SankeyData("China1", "United States", 2.216 * 0.192),
        new SankeyData("China1", "Japan", 2.216 * 0.059),
        new SankeyData("China1", "South Korea", 2.216 * 0.044),

        new SankeyData("Australia", "China", 0.2172 * 0.218),
        new SankeyData("Australia", "United States", 0.2172 * 0.125),
        new SankeyData("Australia", "Argentina", 0.2172 * 0.081),
        new SankeyData("Australia", "Netherlands", 0.2172 * 0.043),

        new SankeyData("Mexico", "United States", 0.409 * 0.799),

        new SankeyData("Japan", "United States", 0.6889 * 0.194),
        new SankeyData("Japan", "China", 0.6889 * 0.19),
        new SankeyData("Japan", "South Korea", 0.6889 * 0.076),

        new SankeyData("Brazil", "China", 0.2172 * 0.218),
        new SankeyData("Brazil", "United States", 0.2172 * 0.125),
        new SankeyData("Brazil", "Argentina", 0.2172 * 0.081),
    }; 
SankeyDatas = datas;

**Comment by wuyang26** [comment] 2024-06-30 04:34
This is the representation of other controls
![image](https://github.com/nxt3AT/sankeydiagram.net/assets/30990704/9a8f694c-cd68-4bdd-901e-16c6b533d8be)

**Comment by JonasDoesThings** [comment] 2024-06-30 08:05
Hi, what input did you enter into https://sankeydiagram.net/?

**Comment by wuyang26** [comment] 2024-07-01 02:33
[sankeydiagram.txt](https://github.com/user-attachments/files/16047317/sankeydiagram.txt)
I tested this website "https://sankeydiagram.net" using the data above ,It has lost some data display
![image](https://github.com/nxt3AT/sankeydiagram.net/assets/30990704/b35e7003-3474-490b-8e30-a5ff94a8cc0c)

The effect displayed by this WPF library is as follows:
![image](https://github.com/nxt3AT/sankeydiagram.net/assets/30990704/947cd954-fc89-4326-ac22-0cf805c411b6)
The data in this WPF library is displayed completely, but there is severe graphic overlap at certain positions.

**Comment by wuyang26** [comment] 2024-07-01 02:40
Especially at nodes "Canada" and "Japan" with severe overlap,you can see that the other control at the top is displayed very well

**Comment by JonasDoesThings** [comment] 2024-07-01 16:39
I see. Thx for providing the data @wuyang26 
The problem with missing data in the output is caused by the small numbers. It can partially be fixed by going into "Settings" and raising the "decimal precision" setting to a higher value.

But yeah, data should not be dropped either way, so I will work on a bugfix for that

**Comment by wuyang26** [comment] 2024-07-02 02:01
Although some data was lost, the graphic avoidance was done very well.

I'm sorry, my previous statement was about the WPF library: https://github.com/iou90/SankeyDiagram 
I sent it to the wrong location. This library is a JavaScript library, not the same.

**Comment by JonasDoesThings** [comment] 2024-07-02 17:18
Great, :) 
I have released v1.4.1 now including a fix for the data-loss

**Closed by JonasDoesThings** 2024-07-02 17:18 UTC
Labels: bug
